---
title: "Surfboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}

library(flexdashboard)
library(tidyverse)
library(plotly)
library(lubridate)
library(DT)
library(here)
library(reticulate)

```

```{r}
# Select a Python environment (optional)
python_env <- NULL  # Set this to the path of your Python executable in virtual env if needed, e.g., "path/to/venv/bin/python" or "venv/Scripts/python"

if (!is.null(python_env)) {
  use_python(python_env, required = TRUE)
}
```


```{r}
# Specify arguments for the Python script
url_input <- NULL  # Set to NULL to use Python's default URL "https://www.surf-report.com/meteo-surf/lacanau-s1043.html"
export_path <- NULL  # Set to NULL to use Python's default, which create a folder "meteo_surf_data/meteo_surf_data.csv" in the current working directory

```


```{r}
# Define the Python script to run
python_script <- "get_surf_data.py"

# Construct the command-line arguments
args <- c(python_script)

if (!is.null(url_input)) {
  args <- c(args, "--url_input", shQuote(url_input))
}

if (!is.null(export_path)) {
  args <- c(args, "--export_path", shQuote(export_path))
}

# Run the Python script using system2()
if (!is.null(python_env)) {
  system2(python_env, args = args)  # Use the specified Python environment
} else {
  system2("python", args = args)  # Use the default Python
}

# Determine the default export path if not specified
if (is.null(export_path)) {
  export_path <- file.path(getwd(), "meteo_surf_data")  # Default path in Python
}

# Check if the output file exists
csv_file <- file.path(export_path, "meteo_surf_data.csv")
if (!file.exists(csv_file)) {
  stop("CSV file not found. The Python script may have failed.")
}

# Read CSV file
raw_data <- read.csv(csv_file)


```



```{r include = FALSE}

# Translation of days and months names from French to English
weekdays_translation_fr <- c("Lundi" = "Monday", "Mardi" = "Tuesday", 
                              "Mercredi" = "Wednesday", "Jeudi" = "Thursday", 
                              "Vendredi" = "Friday", "Samedi" = "Saturday", 
                              "Dimanche" = "Sunday")

# Split the `day` column into "Week day" and "Day" columns and add a fixed year column
translated_data = raw_data %>% 
  separate(day, c("Week day", "Day"), sep = " ", extra = "merge") %>%
  mutate(year = 2024)

# Translate the "Week day" column from French to English using the mapping
translated_data <- translated_data %>%
  mutate(`Week day` = recode(`Week day`, !!!weekdays_translation_fr))


# Translate French month names to English in the "Day" column
translated_data <- translated_data %>%
  mutate(Day = gsub("Janvier", "January", Day),
         Day = gsub("Février", "February", Day),
         Day = gsub("Mars", "March", Day),
         Day = gsub("Avril", "April", Day),
         Day = gsub("Mai", "May", Day),
         Day = gsub("Juin", "June", Day),
         Day = gsub("Juillet", "July", Day),
         Day = gsub("Aout", "August", Day),
         Day = gsub("Septembre", "September", Day),
         Day = gsub("Octobre", "October", Day),
         Day = gsub("Novembre", "November", Day),
         Day = gsub("Décembre", "December", Day))

```


```{r, include = FALSE}
# Combine the "Day", "year", and "hour" columns into a single timestamp column

cleaned_data = translated_data %>%
  mutate(timestamp = dmy_hm(paste(Day, year, hour,  sep = " ")))

# Split the "waves_size" column into "min_wave_size" and "max_wave_size" columns
cleaned_data = cleaned_data %>% separate(waves_size, c("min_wave_size", "max_wave_size"), sep = " - ")

# Extract and clean wind direction data
cleaned_data = cleaned_data %>% 
  separate(wind_direction, c("w","d", "wind_direction"), sep=" ") %>%
  select(-w, -d) %>%
  mutate(day = as_date(timestamp))

cleaned_data

# Select relevant columns, calculate average wave size, and arrange rows by timestamp
surf_data = cleaned_data %>% select(`Week day`, day, timestamp, wind_speed, wind_direction, min_wave_size, max_wave_size,temperature) %>%
  mutate(min_wave_size = as.numeric(min_wave_size), max_wave_size = as.numeric(max_wave_size), avg_wave_size = (min_wave_size+max_wave_size)/2) %>% arrange(timestamp) 

surf_data
```


```{r include=FALSE}
# Computing the best day part 

# Define a function to compute wave scores based on average wave size
score_wave <- function(avg_wave){
  score <- 3.6*avg_wave
  if (score > 10){
    return(10)
  } else{
    return(score)
  }
}

# Define a function to compute wind scores based on average wind speed
score_wind <- function(avg_wind){
  score <- 2*avg_wind/10
  if (score > 10){
    return(10)
  } else{
    return(score)
  }
}

# Group data by day and compute metrics for waves and wind
best_day_data <- surf_data %>% 
  group_by(`Week day`, day) %>% 
  summarize(highest_wave = max(max_wave_size), 
            min_wave = round(min(min_wave_size),2),
            avg_wave = round(mean(avg_wave_size),2), 
            max_wind = round(max(wind_speed),2), 
            avg_wind = round(mean(wind_speed),2),
            min_wind = round(min(wind_speed),2),
            wave_score = round(score_wave(avg_wave),2),
            wind_score = round(score_wind(avg_wind),2),
            score = round(wave_score*0.8 - wind_score*0.2,1)) %>%
  arrange(desc(score))

# Extract the best day with the highest score
best_day <- best_day_data[1, ]
best_day

```

Summary
=======================================================================
<h3 style="margin-top: 0px; margin-bottom-10px; font-weight: 500;"> Best day to practice surf during the coming week  </h3>

Row
-----------------------------------------------------------------------

### Best day

```{r}
# Create a value box to display the best day of the week
valueBox(best_day$`Week day`, caption = format(best_day$day,"%d %B"), icon="fa-calendar-days")
```


### Wave height

```{r}
# Display the highest wave height for the best day
valueBox(paste(best_day$highest_wave, "m", sep = " "), caption = "Highest wave", icon="fa-water")
```

### Wind

```{r}
# Display the average wind speed for the best day
valueBox(paste(best_day$avg_wind, "km/h", sep = " "), caption = "Average wind speed", icon="fa-wind")
```

### Sea score

```{r}
# Display the overall sea score for the best day
valueBox(best_day$score, caption = "Sea quality score", icon="fa-gauge-high")
```

Row {data-height=500}
-----------------------------------------------------------------------

### Highest wave per day

```{r}
best_day_data = best_day_data %>% arrange(day)

# Create a bar plot to visualize the highest wave heights per day
highest_wave_plot = ggplot(best_day_data) +
  geom_bar(aes(x=day, y = highest_wave), stat = 'identity', fill="#6ca3e9") +
  scale_x_date(breaks = "1 day", date_labels = "%d %B") +
  theme_bw() +
  labs(x='', y = "Height (m)")

# Convert ggplot to an interactive plotly object
ggplotly(highest_wave_plot)

```

### Data summary of the week

```{r}
# Display a data table summarizing the week's wave and wind data
datatable(best_day_data %>% select(-score))
```


Row {data-width=350}
-----------------------------------------------------------------------

### Wave size (Daily)

```{r}
# Summarize wave data by day
per_day_data = surf_data %>% 
  mutate(date = as_date(timestamp)) %>%
  group_by(day, date) %>%
  summarise(min_wave_size = min(min_wave_size), max_wave_size = max(max_wave_size), avg_wave_size = mean(avg_wave_size))

# Create a line plot for wave sizes (min, max, average) over time
pivot_t = pivot_longer(per_day_data, cols = c("min_wave_size", "max_wave_size", "avg_wave_size"), names_to = "wave_type", values_to = "value")
wave_plot = ggplot(pivot_t) +
  geom_line(aes(x=date, y = value, color=wave_type)) +
  labs(y="Average wave size (m)", x="") +
  scale_x_date(date_breaks = "1 day", date_labels = "%d %B") +
  theme_bw() + 
  scale_color_discrete(name = "Type", labels = c("Average wave size", "Maximum wave size", "Minimum wave size")) + 
  theme(legend.position = "bottom") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
ggplotly(wave_plot)
```

### Average wind strength (Daily)

```{r}
# Summarize average wind speed by day
per_day_wind = surf_data %>% mutate(day = as_date(timestamp)) %>% group_by(day) %>% summarize(avg_wind_speed = mean(wind_speed))

# Create a line plot for daily wind strength
plot_wind = ggplot(per_day_wind) +
  geom_line(aes(x=day, y = avg_wind_speed), col="orange") +
  scale_x_date(date_breaks = "1 day", date_labels = "%d %B") +
  labs(y="Wind speed (km/h)", x="") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplotly(plot_wind)
```


Detailed
======================================================================
<h3 style="margin-top: 0px; margin-bottom-10px; font-weight: 500;"> Best hour to practice surf during the best day  </h3>

```{r include=FALSE}
# Computing the best hour part 

# Define a function to compute wave scores based on average wave size for detailed hourly data
score_wave_detail <- function(avg_wave_detail){
  score <- 3.6*avg_wave_detail
  if (score > 10){
    return(10)
  } else{
    return(score)
  }
}

# Define a function to compute wind scores based on average wind speed for detailed hourly data
score_wind_detail <- function(avg_wind_detail){
  score <- 2*avg_wind_detail/10
  if (score > 10){
    return(10)
  } else{
    return(score)
  }
}

```

```{r include = FALSE}
# Filter the surf data to only include the best day (determined earlier)
data <- surf_data %>%
  filter(`Week day`== best_day$`Week day`)
  

# Group the data by timestamp and compute hourly metrics
best_moment <- data %>%
  group_by(timestamp,`Week day`) %>%
  summarize(highest_wave_detail = max(max_wave_size), 
            min_wave_detail = round(min(min_wave_size),2),
            avg_wave_detail = round(mean(avg_wave_size),2), 
            max_wind_detail = round(max(wind_speed),2), 
            avg_wind_detail = round(mean(wind_speed),2),
            min_wind_detail = round(min(wind_speed),2),
            wave_score_detail = round(score_wave_detail(avg_wave_detail),2),
            wind_score_detail = round(score_wind_detail(avg_wind_detail),2),
            sea_score_detail = round(wave_score_detail*0.8 - wind_score_detail*0.2,1),
            hour = format(timestamp, "%H:%M"),
            temperature = temperature) %>%
  arrange(desc(sea_score_detail))

# Extract the best hour (highest sea quality score)
best_hour <- best_moment[1,]
best_hour
```

Row
-----------------------------------------------------------------------

### Best hour

```{r}
# Display the best hour as a value box
valueBox(best_hour$hour, caption = best_hour$`Week day`, icon="fa-clock")
```


### Wave height

```{r}
# Display the highest wave height for the best hour
valueBox(paste(best_hour$highest_wave_detail, "m", sep = " "), caption = "Highest wave", icon="fa-water")
```

### Wind

```{r}
# Display the average wind speed for the best hour
valueBox(paste(best_hour$avg_wind_detail, "km/h", sep = " "), caption = "Average wind speed", icon="fa-wind")
```

### Sea score

```{r}
# Display the overall sea quality score for the best hour
valueBox(best_hour$sea_score_detail, caption = "Sea quality score", icon="fa-gauge-high")
```

Row {data-height=500}
-----------------------------------------------------------------------

### Tempertures of the best day

```{r}
# Group the hourly temperature data for the best day
hour_temperature <- best_moment %>% mutate(hour = as.POSIXct(timestamp)) %>% group_by(hour) %>% summarize(temperature = temperature)

# Create a line plot for hourly temperature
plot_temp = ggplot(hour_temperature) +
  geom_line(aes(x= hour, y = temperature), col="purple") +
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M") +
  labs(y="Temperature", x="") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplotly(plot_temp)

```

### Data summary of the day

```{r}
# Prepare the hourly data for a data table
best_time <- best_moment %>% select(-`Week day`) %>% select(hour, everything()) %>% arrange(timestamp)

datatable(best_time %>% group_by(hour) %>% select(-timestamp))
```


Row {data-width=350}
-----------------------------------------------------------------------

### Average wind speed of the day depending on the wind direction

```{r}
# Compute average wind speed for each wind direction
wind_direction_data <- data %>% group_by(wind_direction) %>% summarize(average_wind = round(mean(wind_speed),2))

# Create a bar plot to visualize average wind speed by direction
wind_direction_plot <- ggplot(wind_direction_data) +
  geom_bar(aes(x=wind_direction, y = average_wind), stat = 'identity', fill="orange", width = 0.3) +
  theme_bw() +
  coord_flip()+
  labs(x='', y = "Average wind speed (km/h)")

ggplotly(wind_direction_plot)

```

### Quality scores of the sea, waves and wind (Hourly)

```{r}
# Extract hourly scores for wind, wave, and sea quality
per_hour_scores = best_moment %>% 
   select(timestamp, hour, wind_score_detail, wave_score_detail, sea_score_detail)

# Pivot the data to long format for plotting
pivot <- pivot_longer(per_hour_scores, cols = c("wind_score_detail", "wave_score_detail", "sea_score_detail"), names_to = "scores", values_to = "value")

# Create a line plot for hourly scores
scores_hour <- ggplot(pivot) +
  geom_line(aes(x=timestamp, y = value, color=scores)) +
  labs(y="Scores", x="") +
  scale_x_datetime(date_breaks = "1 hour", date_labels = "%H:%M") +
  theme_bw() + 
  scale_color_discrete(name = "Type", labels = c("Wind score per hour", "Wave score per hour", "Total score per hour")) + 
  theme(legend.position = "bottom") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplotly(scores_hour)

```


